#应用(服务)名称
spring:
  application:
    name: springcloud-eureka-consumer

server:
  port: 8763

#注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    #续约频率
    lease-renewal-interval-in-seconds: 10
    #失效时间
    lease-expiration-duration-in-seconds: 30