

server:
  port: 8761
#注册中心默认端口就是8761，也可通过下面的方式定义其他端口
#eureka.client.serviceUrl.defaultZone=http://localhost:${server.port}/eureka/

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  instance:
    #续约频率
    lease-renewal-interval-in-seconds: 10
    #失效时间
    lease-expiration-duration-in-seconds: 30